---
- hosts: R1
  gather_facts: False
  connection: local

  tasks: 
   - name: ping 192.168.1.252
     ios_command:
       commands: 
         - ping 192.168.1.252
     register: ping_result

   - name: show result
     copy:
       content: "{{ ping_result.stdout[0] }}"
       dest: "/etc/ansible/results/ping2.txt"
     when : ping_result.stdout[0].find('Success rate is 100 percent') != -1 
     
