

---
- hosts: R1
  gather_facts: False
  connection: local

  tasks: 
   - name: ping 192.168.1.252
     ios_command:
       commands: 
         ping 192.168.1.252
     register: ping_result

   - name: show result
     shell: echo ping_result
     when: ping_result.stdout.find('2 packets received') != -1
