---
- hosts: R1
  gather_facts: False
  connection: local

  tasks: 
   - name: ping 192.168.1.252
     ios_command:
       commands: 
         - ping 192.168.1.252
     register: ping_result

- hosts: ansibleServer
  gather_facts: False
  connection: local
  
  tasks: 
  - name: show result
    command: echo get_serial_number
    register: serial_number_result
    when: ping_result.stdout[0].find('Success rate is 100 percent') != -1    
    
  - name: Save ouput to /etc/ansible/results
    copy:
      content: "{{ ping_result.stdout[0] }}"
      dest: "/etc/ansible/results/ping5.txt"
       
    
  
