---
- hosts: R1
  gather_facts: False
  connection: local

  tasks: 
   - name: ping 192.168.1.252
     ios_command:
       commands: 
        - ping 192.168.1.252
     register: ping_result
     
- hosts: ansibleServer
  gather_facts: False
  connection: local
  
  tasks:      
   - name: get serial number
     command: snmpwalk -v2c -c snmpString 192.168.1.253 .iso.3.6.1.4.1.9.3.6.3
     register: serialNumber
   - name: Save results
     copy:
       content: "{{hostvars['R1']['ping_result'].stdout[0]}} {{ serialNumber.stdout }}"
       dest: "/etc/ansible/results/serialNumber.txt"
     when: hostvars['R1']['ping_result'].stdout[0].find('Success rate is 100 percent') != -1    
   
