---
- hosts: R1
  gather_facts: False
  connection: local

  tasks: 
   - name: ping 192.168.1.252
     ios_command:
       commands: 
        - ping 192.168.1.252
     register: ping_result
     
- hosts: ansibleServer
  gather_facts: False
  connection: local
  
  tasks:      
   - name: Save ouput to /etc/ansible/results
     copy:
       content: "{{ hostvars['R1']['ping_result'].stdout[0] }}"
       dest: "/etc/ansible/results/ping8.txt"
     when: hostvars['R1']['ping_result'].stdout[0].find('Success rate is 110 percent') != -1    
   
