

---
- hosts: R1
  gather_facts: False
  connection: local

  tasks: 
   - name: ping 192.168.1.252
     ios_command:
       commands: 
         - ping 192.168.1.252
     register: ping_result

   - name: show result
     shell: echo "{{ show_run.stdout[0] }}" > /etc/ansible/results/ping_result.res
