---
- hosts: R1
  gather_facts: False
  connection: local

  tasks: 
   - name: Show Run R1
     ios_command:
       commands:
         - show run
     register: show_run

   - name: Save ouput to /etc/ansible/results
     copy:
       content: "{{ show_run.stdout[0] }}"
       dest: "/etc/ansible/results/show_run_{{inventory_hostname}}.txt"
       
   - name: Show Ver R1
     ios_command:
       commands:
         - show ver
     register: show_ver

   - name: Save ouput to /etc/ansible/results
     copy:
       content: "{{ show_ver.stdout[0] }}"
       dest: "/etc/ansible/results/show_ver_{{inventory_hostname}}.txt"
       
   - name: Show Int R1
     ios_command:
       commands:
         - show interface brief
     register: show_int

   - name: Save ouput to /etc/ansible/results
     copy:
       content: "{{ show_int.stdout[0] }}"
       dest: "/etc/ansible/results/show_int_{{inventory_hostname}}.txt"
